[workspace]
resolver = "2"
members = [
    "sending",
    "receiving",
    "shared_types",
]

[workspace.package]
authors = ["Grant Gardner"]

# These settings make it as small as possible
[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1
